#========================= Filebeat inputs options ============================
- type: log
  paths:
    - /var/log/auth.log
    - /var/log/kern.log
    - /var/log/syslog
  fields:
    ES_INDEX: system
  fields_under_root: true
  tags: ["syslog"]
  multiline:
    pattern: '^\['
    match: after
  
- type: log
  paths:
    - /var/log/bash_audit.log
  fields:
    ES_INDEX: system
    is_customer_data: true
  fields_under_root: true
  tags: ["bash_audit"]
  multiline:
    pattern: '^\['
    match: after

%{ if kube_system_log_enabled }
- type: log
  paths:
    - /var/log/kube-proxy.log
    - /var/log/kube-apiserver.log
    - /var/log/kube-controller-manager.log
    - /var/log/kube-scheduler.log
    - /var/log/kube-apiserver-audit.log
  fields:
    ES_INDEX: system
  fields_under_root: true
  tags: ["kube_system"]
  multiline:
    pattern: '^\['
    match: after
%{ endif }

%{ if kube_audit_log_enabled }
- type: log
  paths:
    - /var/log/kube-apiserver-audit.log
  fields:
    ES_INDEX: kube-audit
    is_customer_data: true
  fields_under_root: true
  json:
    keys_under_root: true
    message_key: message
    ignore_decoding_error: true
  tags: ["kube_audit"]
  multiline:
    pattern: '^\['
    match: after
%{ endif }

- type: container  
  paths:
    - "/var/lib/docker/containers/*/*.log"
  fields_under_root: true
  max_bytes: 524288
  json:
    keys_under_root: true
    message_key: message
    ignore_decoding_error: true
  tags: ["k8s_logs"]
  processors:
    - add_kubernetes_metadata:
        in_cluster: true
